// generalIcons//COLOR
export * from './generalIcons/fullColorStyle/AlerBotColor';
export * from './generalIcons/fullColorStyle/EditColor';
export * from './generalIcons/fullColorStyle/CoinColor';
export * from './generalIcons/fullColorStyle/CopyColor';
export * from './generalIcons/fullColorStyle/DocColor';
export * from './generalIcons/fullColorStyle/ArticleColor';
export * from './generalIcons/fullColorStyle/AudioColor';
export * from './generalIcons/fullColorStyle/ChartColor';
export * from './generalIcons/fullColorStyle/CommentColor';
export * from './generalIcons/fullColorStyle/DashboardColor';
export * from './generalIcons/fullColorStyle/DeleteColor';
export * from './generalIcons/fullColorStyle/GobeColor';
export * from './generalIcons/fullColorStyle/HeartColor';
export * from './generalIcons/fullColorStyle/InfoColor';
export * from './generalIcons/fullColorStyle/MediaColor';
export * from './generalIcons/fullColorStyle/MoreCircleColor';
export * from './generalIcons/fullColorStyle/NewsColor';
export * from './generalIcons/fullColorStyle/NotificationColor';
export * from './generalIcons/fullColorStyle/PlusColor';
export * from './generalIcons/fullColorStyle/Plus1Color';
export * from './generalIcons/fullColorStyle/Plus2Color';
export * from './generalIcons/fullColorStyle/RocketColor';
export * from './generalIcons/fullColorStyle/SearchColor';
export * from './generalIcons/fullColorStyle/SendColor';
export * from './generalIcons/fullColorStyle/SettingsColor';
export * from './generalIcons/fullColorStyle/SubscribeColor';
export * from './generalIcons/fullColorStyle/SwapColor';
export * from './generalIcons/fullColorStyle/TelegramColor';
export * from './generalIcons/fullColorStyle/TimeColor';
export * from './generalIcons/fullColorStyle/TwitterColor';
export * from './generalIcons/fullColorStyle/WalletColor';
export * from './generalIcons/fullColorStyle/WebinarColor';
export * from './generalIcons/fullColorStyle/Check';
// generalIcons//STANDARD
export * from './generalIcons/filledStyle/AlertBotStandard';
export * from './generalIcons/filledStyle/EditStandard';
export * from './generalIcons/filledStyle/CoinStandard';
export * from './generalIcons/filledStyle/CopyStandard';
export * from './generalIcons/filledStyle/ArticleStandard';
export * from './generalIcons/filledStyle/AudioStandard';
export * from './generalIcons/filledStyle/ChartStandard';
export * from './generalIcons/filledStyle/CommentStandard';
export * from './generalIcons/filledStyle/DashboardStandard';
export * from './generalIcons/filledStyle/DeleteStandard';
export * from './generalIcons/filledStyle/HeartStandard';
export * from './generalIcons/filledStyle/InfoStandard';
export * from './generalIcons/filledStyle/MediaStandard';
export * from './generalIcons/filledStyle/MoreCircleStandard';
export * from './generalIcons/filledStyle/NewsStandard';
export * from './generalIcons/filledStyle/NotificationStandard';
export * from './generalIcons/filledStyle/PlusStandard';
export * from './generalIcons/filledStyle/RocketStandard';
export * from './generalIcons/filledStyle/SearchStandard';
export * from './generalIcons/filledStyle/SendStandard';
export * from './generalIcons/filledStyle/SettingsStandard';
export * from './generalIcons/filledStyle/SubscribeStandard';
export * from './generalIcons/filledStyle/SwapStandard';
export * from './generalIcons/filledStyle/TelegramStandard';
export * from './generalIcons/filledStyle/TimeStandard';
export * from './generalIcons/filledStyle/TwitterStandard';
export * from './generalIcons/filledStyle/WalletStandard';
export * from './generalIcons/filledStyle/WebinarStandard';
export * from './generalIcons/filledStyle/DownloadStandard';
// navigationIcons
export * from './navigationIcons/ArrowDownIcon';
export * from './navigationIcons/ArrowLeftIcon';
export * from './navigationIcons/ArrowRightIcon';
export * from './navigationIcons/ArrowUpIcon';
export * from './navigationIcons/NoticeIcon';
export * from './navigationIcons/LinkIcon';
export * from './navigationIcons/CrossIcon';
export * from './navigationIcons/ArrowLeftSquareIcon';
export * from './navigationIcons/ArrowRIghtSquareIcon';
export * from './navigationIcons/ChevronDownIcon';
export * from './navigationIcons/ChevronLeftIcon';
export * from './navigationIcons/ChevronRightIcon';
export * from './navigationIcons/ChevronUpIcon';
export * from './navigationIcons/RefreshIcon';
// chains
export * from './chains/Arbitrum';
export * from './chains/Avalanche';
export * from './chains/Binance';
export * from './chains/Cielo';
export * from './chains/Curve';
export * from './chains/Ethereum';
export * from './chains/Fantom';
export * from './chains/Near';
export * from './chains/Optimism';
export * from './chains/Polygon';
export * from './chains/Sushiswap';
export * from './chains/Terra';
export * from './chains/Uniswap';
export * from './chains/UniWhales';
export * from './chains/Boba';
export * from './chains/Aurora';
export * from './chains/Metis';
// chains color
export * from './chains/fullColorStyle/AuroraColor';
export * from './chains/fullColorStyle/UniswapV2Color';
export * from './chains/fullColorStyle/UniswapV3Color';
export * from './chains/fullColorStyle/BobaColor';
export * from './chains/fullColorStyle/CieloColor';
export * from './chains/fullColorStyle/ArbitrumColor';
export * from './chains/fullColorStyle/AvalancheColor';
export * from './chains/fullColorStyle/BinanceColor';
export * from './chains/fullColorStyle/CurveColor';
export * from './chains/fullColorStyle/EthereumColor';
export * from './chains/fullColorStyle/EtherscanColor';
export * from './chains/fullColorStyle/FantomColor';
export * from './chains/fullColorStyle/HarmonyColor';
export * from './chains/fullColorStyle/MetaMaskColor';
export * from './chains/fullColorStyle/MetisColor';
export * from './chains/fullColorStyle/NearColor';
export * from './chains/fullColorStyle/OptimismColor';
export * from './chains/fullColorStyle/PolygonColor';
export * from './chains/fullColorStyle/SushiswapColor';
export * from './chains/fullColorStyle/TerraColor';
export * from './chains/fullColorStyle/WalletConnectColor';
export * from './chains/fullColorStyle/UniWhalesColor';
export * from './chains/fullColorStyle/0xColor';

export * from './chains/fullColorStyle/OneInchV3';
export * from './chains/fullColorStyle/OneInchV4';
export * from './chains/fullColorStyle/BalancerColor';
export * from './chains/fullColorStyle/BancorColor';
export * from './chains/fullColorStyle/ParaSwapV4';
export * from './chains/fullColorStyle/ParaSwapV5';
// coins
export { Dai } from './tokens/DAI';
export { Doge } from './tokens/DOGE';
export { Usdc } from './tokens/USDC';
export { Usdt } from './tokens/USDT';
export { Weth } from './tokens/WETH';
// placeholder
export { StarIcon } from './placeholder/StarIcon';
