env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
  - airbnb-typescript
parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2021
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules: {
  "react/require-default-props": off,
  "jsx-a11y/label-has-associated-control": off,
  "react/function-component-definition":
    [2, { "namedComponents": "arrow-function" }],
  "import/no-extraneous-dependencies": ["error", { "devDependencies": true }],
  "import/prefer-default-export": "off",
  "react/jsx-props-no-spreading": "off",
  "@typescript-eslint/no-unused-expressions": ["off"],
}
