export const ModalMockDataLatestAnnouncements = [{
  id: 24, title: 'Over 10,000 EVM Tracker Users', datetime: 1654280372000.0, text: '\ud83d\udcb8 EVM Tracker (Wallet Alerts) surpasses 10K users</br>\r\n\ud83d\udd35 EVMOS support is live on EVM Tracker</br>\r\n\u26d3\ufe0f Tracking 11 chains</br>\r\n\r\n\ud83c\udf09 Group mode enabled. 1 click add for to any Telegram group. Great for NFT friends, funds, and influencers who want to share the wallet alerts with their audience</br></br>\r\n\ud83c\udf81 NEAR bot launching very soon</br>\r\n\r\n\ud83d\udfe2#BUIDL', image: 'https://d1yaedilx42rkd.cloudfront.net/media/2022/06/03/june.jpg',
}, {
  id: 23, title: '\u2b50 Product Releases', datetime: 1646443982000.0, text: '\ud83d\udcb8 Wallet Alerts Bot Best In Class</br>\r\n\ud83d\udd35 10 EVM Chains, EVMOS Soon. Unlimited Wallets</br></br>\r\n\r\n\ud83c\udf81 NEAR Foundation Grant Received</br>\r\n\ud83c\udf09 Aurora Bridge Tracker Live </br></br>\r\n\r\n\ud83d\udcbbNew CMS - Research, interviews, and community calls all in one place.</br>\r\n\ud83d\udfe2Sprint to V2 is next ...', image: 'https://d1yaedilx42rkd.cloudfront.net/media/2022/03/05/march22.jpg',
}, {
  id: 21, title: 'DAO Energy, Tooling, + Content are on \ud83d\udd25', datetime: 1635529248000.0, text: 'Highlights </br>\r\n\ud83d\udfe2 Major infrastructure upgrades </br>\r\n\ud83d\udd35 Pro bridge dashboard soon </br>\r\n\ud83d\udfe2 UniWhales research is here - VC Deal analysis, Governance, Farming. </br>\r\n\ud83d\udd35 # of DAO Members and engagement at an all-time high', image: 'https://d1yaedilx42rkd.cloudfront.net/media/2021/10/29/uuu22n.png',
}, {
  id: 20, title: 'Bridge Whales', datetime: 1630420182000.0, text: '\ud83d\udfe2 We launched free bridge trackers for four blockchains: </br>\r\n\r\n\ud83d\udd35 Terra, Polygon, Avalanche, and Fantom </br>\r\n\r\n\ud83d\udfe2 Up next for DAO members - upgraded wallet analysis/profitability, and Social Sonar bot improvements.', image: 'https://d1yaedilx42rkd.cloudfront.net/media/2021/08/31/puente.png',
}, {
  id: 19, title: 'NFT Mints, Terra, Polygon', datetime: 1628864080000.0, text: 'UniWhales fam, </br></br>\r\n\r\n\ud83d\udfe2Wallet Profitability for ETH L1 - live </br>\r\n\r\n\ud83d\udd35ParaSwap (ETH and BSC integration) - live  </br>\r\n\r\n\ud83d\udfe2Balancer V2 - live\r\n </br></br>\r\n\r\nNext week: </br>\r\n\ud83c\udf1fTerra Dashboard </br>\r\n\r\n\ud83d\udd36NEW Polygon Dashboard\r\n </br>\r\n\r\n^^Will launch a free version of each to help gain publicity and users for UniWhales. Later will launch a paid version.\r\n </br></br>\r\n\r\nDrip landing page and sign up for private beta is imminent.', image: 'https://d1yaedilx42rkd.cloudfront.net/media/2021/08/13/Fri13.png',
}, {
  id: 18, title: '\ud83d\udd0b Social Sonar BETA is live', datetime: 1626810373000.0, text: 'Find new and under the radar projects and $TOKENS in DeFi/NFTs by tracking influential Twitter accounts and their Twitter activity.</br></br>\r\n\r\n\ud83d\udea7 Currently in beta, a web app dashboard with more data and features is under construction. </br></br>\r\n\r\nAs we fine-tune the product, we will filter and add in relevant updates a few times per day.\r\n\r\n\ud83d\udd11 While in beta, access is for pro and whale members. </br></br>\r\nWhen we launch the dashboard, will move to \ud83d\udc33 tier\r\n</br></br>\r\nUp next: </br>\ud83d\udfe2Balancer V2 (ETH integration)</br>\ud83d\udd35ParaSwap (ETH integration)</br> \ud83d\udfe2A Terra ecosystem tool', image: 'https://d1yaedilx42rkd.cloudfront.net/media/2021/07/20/photo_2021-07-20_11-36-31_CmvaRFd.jpg',
}, {
  id: 17, title: 'V 1.3.0 is live', datetime: 1624969938000.0, text: '\ud83d\udda5 Trending Contracts, Enhanced Token View</br></br>\r\n\r\n\ud83d\udc33 Tier Feature - Find new Ethereum contracts from our curated list of power traders, influencers (DeFi + NFTs), and top yield farmers.</br>\r\n\ud83e\uddeb Enhanced token view on ETH L1 tokens</br></br>\r\n\r\n-\ud83d\udcb0Wallet analysis tool, quickly see Ethereum, BSC, and Polygon balances using Debank API</br>\r\n\r\n</br>\r\n**Polygon charting and enhanced wallet statistics will be added in next release</br>', image: 'https://d1yaedilx42rkd.cloudfront.net/media/2021/06/29/1.32.0.png',
}, {
  id: 16, title: 'V 1.2.0 is live', datetime: 1623518060000.0, text: '\ud83d\udda5 Web App V 1.2.0 is live! </br></br>\r\n\r\n-LP Add/Remove dashboard for Polygon DEXes (QuickSwap, SushiSwap, Paraswap, Dfyn*) </br>\r\n-LP Add/Remove dashboard for PancakeSwap on BSC</br></br>\r\n\r\n-Uniswap V3\ud83d\udcc8 included in the TVL and Volume charts**</br>\r\n-\ud83d\udcfa Whalenars now embedded inside the app</br>\r\n-And we now have the share option enabled </br>\r\n\ud83e\uddf7 You can now share links to specific dashboard views in the DAO or to other DAO members</br>\r\n</br>\r\n*Dfyn added in this release. </br>\r\n**Quickswap Volume and TVL data will be added in the next release</br>', image: 'https://d1yaedilx42rkd.cloudfront.net/media/2021/06/12/uw1.png',
}, {
  id: 15, title: 'Epic Content, Polygon', datetime: 1622135703000.0, text: 'Content and Tooling Updates</ br>\r\n<ul>\r\n<li>New Degen Newsletter here inside the web app!</li>\r\n<li>RedPhone interview (written) - this weekend</li>\r\n<li>Balancer webinar replay available here in the web app </li>\r\n<li>Polygon Dashboard  - very soon</li>\r\n</ul>', image: 'https://d1yaedilx42rkd.cloudfront.net/media/2021/05/27/update2.png',
}, {
  id: 14, title: 'V 1.0.0 is LIVE', datetime: 1621461691000.0, text: 'Our most comprehensive update ever. </ br>\r\n<ul>\r\n<li>Powerful DEX stats and token stats</li>\r\n<li>Token outflows combined  + ranked for winners/losers (Uni V2 + V3 + SUSHI), 24h + 7d</li>\r\n<li>ETH + BSC tokens clickable into a whale TX search</li>\r\n<li>LP Add/Remove outflows clickable into Liquidity search</li>\r\n<li>DEX Vol/TVL for Pancake, Uniswap, + SushiSwap</li>\r\n<li>New / Unknown tokens list 24h + 7d</li>\r\n<li>Cross-chain favorites list (Ethereum + BSC)</li>\r\n</ul>', image: 'https://d1yaedilx42rkd.cloudfront.net/media/2021/05/19/v1-release.png',
}, {
  id: 13, title: 'Week of May 17th', datetime: 1621258268000.0, text: 'Community Call VC Deals (TG Clubhouse)      **      Major Web App updates', image: 'https://d1yaedilx42rkd.cloudfront.net/media/2021/05/17/update.png',
}, {
  id: 11, title: 'Degen Newsletter - Issue #1', datetime: 1619741236000.0, text: '<a href="https://mgate.io/go/OEgbJa8S17WB/">Read here</a> Featuring farming picks, stables, new tools, new tech, trading theses, Solana + more.', image: 'https://d1yaedilx42rkd.cloudfront.net/media/2021/05/13/degen-news.png',
}, {
  id: 10, title: 'Power Brokers V2 Live', datetime: 1617994069000.0, text: '\ud83d\udfe2 Enhanced, more intuitive statistics\r\n-7 day stats\r\n-Net outflow per token\r\n-Rare token swaps\r\n\r\n\ud83d\udd35 LP Add/Remove tab', image: 'https://d1yaedilx42rkd.cloudfront.net/media/2021/05/15/powerbrokersv2.png',
}, {
  id: 9, title: 'RedPhonshipSaurus V2 - Charting', datetime: 1617371214000.0, text: 'Charting, recent tx, LP add/remove are now integrated into RedPhonshipSaurus.\r\n\r\nClick on the token or chart symbol to load the charting module.', image: 'https://d1yaedilx42rkd.cloudfront.net/media/2021/05/13/charting.png',
}, {
  id: 8, title: 'NFT Whales (next 10 days)', datetime: 1617220790000.0, text: 'GMoneyNFT and UniWhales team have the list of top NFT players ready.\r\n\r\nWe are going to start building out the channel soon.\r\n\r\nLook for the NFT whales TG channel to catch mints and drops next week. (Whale tier)', image: '',
}, {
  id: 7, title: 'VC Deal Tracker - LIVE', datetime: 1617219643000.0, text: 'We launched yesterday and over 150 million deals with other 50+ investors.\r\nClick on "pro/whale" and join our channel today.', image: '',
}, {
  id: 6, title: 'VC Deal Tracker - Coming Soon', datetime: 1616429324000.0, text: 'The @DeFi_Rooster is bringing his database of Crypto VCs to the UniWhales platform. \r\n\r\nWe will track, monitor, and report-on investment activity, so you can get a headstart on promising VC-backed projects. \r\n\r\nDiffering from our current products, it will start as an off-chain tool aggregating a variety of data points.', image: '',
}, {
  id: 5, title: 'Upcoming Whalenar Tuesday 3/23', datetime: 1616112711000.0, text: 'How to use UniWhales v 0.1.0 and Q+A with @blocksecco\r\n\ud83d\uddd3 Tuesday @ 9:30 AM New York time\r\n\r\nMike Ghen is a UniWhales team member and built the backend of RedPhonshipSaurus and Power Brokers.He also runs decentralized funds on iFund, is a long time miner, runs a blockchain meetup group, and teaches Solidity to Drexel and UPenn students.', image: '',
}, {
  id: 4, title: 'Aaron Wright of The LAO / Flamingo DAO', datetime: 1615940648000.0, text: 'The LAO is a Delaware LLC DAO run by computational lawyers that has over invested over 27 million USD worth of Ether contributed by members, all via decentralized governance and investing in many projects, quite a few that have been discussed in the UniWhales DAO.\r\n\r\nProjects like Tornado.Cash, IDLE Finance, Debank + More.\r\n\r\nTomorrow Wednesday @ 9 AM New York time.', image: '',
}, {
  id: 3, title: 'ETH Global NFT Hack', datetime: 1615492856000.0, text: 'UniWhales team members are entering a project into the ETH Global NFTHack next weekend. We are excited to participate and hopefully add a new idea to the exciting world of NFTs. Final judging is on March 21st. Wish us luck!', image: '',
}, {
  id: 2, title: 'GMoney NFT <> UniWhales', datetime: 1615419697000.0, text: 'You probably saw - we have agreed to a partnership with GMoney NFT to build out our NFT tooling.\r\nThe first project is a Power Brokers NFT style. GMoney will maintain a list of the top NFT players, artists, etc, and we will build out a Telegram alerts channels to help find new mints and drops.', image: '',
}];
